#!/bin/bash

export PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/bin:/bin:$PATH"

if [ -z "$1" ];then
   echo "$0 total|biggest|smallest|average|number"
   exit 1
fi

ps auxwwww|awk -v what="$1" '
   BEGIN{
     a=0;
     c=0;
     max=0;
     min=0;
   }
   /\/httpd2-prefork|\/apache2|\/httpd/{
     a = a + $6; 
     c++
     if ($6 > max){
	max = $6;
     }
     if ((min == 0) || (min > $6)){
	min = $6;
     }
    }
   END{
     printf("RSS MEMORY\n");
     printf("----------------------------------------------------\n");
     printf("TOTAL             : %i mbytes\n",a/1024)
     printf("BIGGEST CHILD     : %i mbytes\n",max/1024)
     printf("SMALLEST CHILD    : %i mbytes\n",min/1024)
     printf("AVERAGE CHILD     : %i mbytes\n",a/c/1024)
     printf("NUMBER OF CHILDS  : %i processes\n",c)
   }'

