#!/bin/bash

set -x
sudo puppet agent --enable
sudo puppet agent --test
RET="$?"
set +x

echo 
echo
if [ "$RET" == "0" ];then
	echo "SUCCESS"
   exit $RET
elif [ "$RET" == "1" ];then
	echo "FAILED"
   exit $RET
elif [ "$RET" == "2" ];then
	echo "SUCCESS"
   exit 0
else
	echo "FAILED"
   exit $RET
fi

