name: Common Steps

on:
  workflow_call: # Enables this workflow to be called by others
    inputs:
      build-type:
        description: "Type of build (e.g., debug, release)"
        type: string
        required: true

jobs:
  common-steps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable # or specify the desired version
    - name: Build project
      run: cargo build --release
    - name: Package tarball
      run: |
        mkdir -p release/hostctl release/hostctl/misc
        cp target/release/hostctl release/hostctl/
        cp -av recipe release/hostctl/recipe/
        target/release/hostctl generate-completions bash > release/hostctl/misc/hostctl_bash_completion.sh
        target/release/hostctl generate-completions zsh > release/hostctl/misc/hostctl_zsh_completion.sh
        target/release/hostctl generate-completions fish > release/hostctl/misc/hostctl_fish_completion.sh
        cd release
        tar tzvf ../hostctl-v${{ github.ref_name }}.tar.gz hostctl
    - name: Create release and upload it
      uses: ncipollo/release-action@v1
      if: ${{ inputs.build-type == 'release' }}
      with:
        artifacts: "hostctl-v${{ github.ref_name }}.tar.gz"
